---
title: "Tarea #5 - Julio Cesar Rustrian Monterroso"
output: html_notebook
---

#cargando librerias
```{r}
library(tidyverse)
```

#cargando archivos de trabajo 
```{r}
questions <- read_csv("questions.csv")
answers <- read_csv("answers.csv")
tags <- read_csv("tags.csv")
question_tags <- read_csv("question_tags.csv")

questions
answers
tags
question_tags
```
#paso 1 - Left-joining questions and tags
```{r}
questions_with_tags <- questions %>%
  left_join(question_tags, by = c("id" = "question_id")) %>% #paso 1.1
  left_join(tags, by = c("tag_id" = "id")) %>% #paso 1.2
  replace_na(list(tag_name = "only-r")) #paso 1.3

questions_with_tags
```
#paso 2 - Comparing scores across tags
```{r}
questions_with_tags %>%
  group_by(tag_name) %>% #paso 2.1
  summarize(mean_score = mean(score)) %>% #paso 2.2
  arrange(desc(mean_score))
```
#paso 3 - Finding gaps between questions and answers
```{r}
questions %>%
  inner_join(answers, by = c("id" = "question_id"), suffix = c("_question", "_answer")) %>% #paso 3.1
  mutate(gap = creation_date_answer - creation_date_question) #paso 3.2
```
#paso 4 - Joining question and answer counts
```{r}
answers_counts <- answers %>% #paso 4.1
  count(question_id) %>%
  arrange(desc(n))

answers_counts

question_answer_counts <- questions %>% #paso 4.4
  left_join(answers_counts, by = c("id" = "question_id")) %>% #paso 4.2
  replace_na(list(n = 0)) #paso 4.3

question_answer_counts
```
#paso 5 - Joining questions, answers, and tags
```{r}
question_tags %>%
  inner_join(question_answer_counts, by = c("question_id" = "id")) %>% #paso 5.1
  inner_join(tags, by = c("tag_id" = "id")) #paso 5.2
```






