---
title: "Tarea 4 Julio Cesar Rustrian Monterroso"
output: html_notebook
---

```{r}
library(tidyverse)
diamonds <- read.csv("diamonds.csv")
```
```{r}
diamonds %>%
  filter(price > 1000) %>%
  count(cut)

str(diamonds)
```
#paso 1 - Dispersión
```{r}
  ggplot(diamonds, aes(x=carat, y=price)) + #paso 1.1
  geom_point()

  ggplot(diamonds, aes(x=carat, y=price, color = clarity)) + #paso 1.2, 1.3
  geom_point()
```

#paso 2 - Histograma
```{r}
ggplot(diamonds, aes(x=price))+ #paso 2.1
  geom_histogram(bins = 40)

ggplot(diamonds, aes(x=price)) + #paso 2.2
  geom_histogram(bins = 40) +
  scale_x_log10()
```

#Paso 3 - Boxplot
```{r}
ggplot(diamonds, aes(x = cut, y = price)) + #paso 3.1
  geom_boxplot()

ggplot(diamonds, aes(x = cut, y = price, fill = cut)) + #paso 3.2
  geom_boxplot()
```

#Paso 4 - Faceting
#Paso 4.1 - Filtrado y asignación
```{r}
filtered_price <- diamonds %>%
  filter(price > 1000) %>%
  filter(cut %in% c("Good","Ideal","Premium"))

  #filter(cut == c("Good","Ideal","Premium")) ----- ¿Porqué de esta forma muestra menos datos?

filtered_price
```
#Paso 4.2 al 4.4 - Faceting Gráfico
```{r}
ggplot(filtered_price, aes(x = cut, y = depth)) + #paso 4.3
  geom_col() +
  facet_wrap(~clarity)

ggplot(filtered_price, aes(x = cut, y = depth, fill = clarity)) + #paso 4.4
  geom_col() +
  facet_wrap(~clarity)
```
#Paso 5 - Grouping and Summarizing
#Paso 5.1 - Agrupamiento y summarize de medias
```{r}
median_dimension_diamon <- diamonds %>%
  group_by(cut) %>%
  summarize(mediaX = median(x), mediaY = median(y), mediaZ = median(z))

median_dimension_diamon
```
#Paso 5.2 - Filtrado, agrupamiento y summarize de max y min
```{r}
cut_premium <- diamonds %>%
  filter(cut == "Premium") %>%
  group_by(clarity) %>%
  summarize(minPrice = min(price), maxPrice = max(price))

cut_premium
```

#Paso 5.3 - Gráfico de barras
```{r}
ggplot(cut_premium, aes(x = clarity, y = maxPrice, fill = clarity )) +
  geom_col()
```







